version: '3.7'

services:
  service1:
    image: docker.io/library/service:healthy1

  service2:
    image: docker.io/library/service:healthy1

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8182:80"
    depends_on:
      - service1